### ISSUE TITLE
Order of values for subtraction operators

### ISSUE THREAD

**Issue by rdewijn** [tercen/logfoldchange_app#3]
Is the order of the values for the subtraction operator unambiguous?

i.e is it guaranteed that control is always subtracted from treatment and not the other way around?

**Comment by ginberg** [comment]
hi @rdewijn, the [minus operator](https://github.com/tercen/minus_operator) subtracts the second value (layer) from the first value (layer). In the view I have set the control on the second layer, so it works well. Since the view is build into the app, it should work well, unless one is manually changing the layers in the view. Does this work for you?

**Comment by rdewijn** [comment]
OK
